name: Build with buildah and Push to Container Registry
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .forgejo/**
      - README.md
    branches:
      - main
    tags:
      - '**'
jobs:
  build_and_push:
    runs-on: default
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
      - name: Build the Image
        uses: https://github.com/redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.IMAGE_NAME }}
          tags: ${{ env.GITHUB_REF_NAME }} latest
          platforms: linux/amd64,linux/arm64
          containerfiles: |
            ./Containerfile
      - name: Login to the registry
        uses: https://github.com/redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          auth_file_path: $HOME/.docker/config.json
      - name: Push the image to the registry
        uses: https://github.com/redhat-actions/push-to-registry@v2
        with:
          tags: ${{ vars.IMAGE_NAME }}:${{ env.GITHUB_REF_NAME }}
      - name: Push tags to latest
        if: startsWith(github.ref, 'refs/tags/v')
        uses: https://github.com/redhat-actions/push-to-registry@v2
        with:
          tags: ${{ vars.IMAGE_NAME }}:latest
      - name: Check if .dockerhub exists
        if: startsWith(github.ref, 'refs/tags/v')
        id: check_dockerhub
        uses: https://github.com/andstor/file-existence-action@v1
        with:
          files: '.dockerhub'
      - name: Tag image for dockerhub
        if: steps.check_dockerhub.outputs.files_exists == 'true'
        run: |
          buildah tag ${{ vars.IMAGE_NAME }}:${{ env.GITHUB_REF_NAME }} docker.io/${{ secrets.DOCKERHUB_USER }}/${{ vars.DOCKERHUB_IMAGE_NAME }}:${{ env.GITHUB_REF_NAME }}
          buildah tag ${{ vars.IMAGE_NAME }}:${{ env.GITHUB_REF_NAME }} docker.io/${{ secrets.DOCKERHUB_USER }}/${{ vars.DOCKERHUB_IMAGE_NAME }}:latest
      - name: Login to Dockerhub
        if: steps.check_dockerhub.outputs.files_exists == 'true'
        uses: https://github.com/redhat-actions/podman-login@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          auth_file_path: $HOME/.docker/config.json
      - name: Push to Dockerhub
        if: steps.check_dockerhub.outputs.files_exists == 'true'
        uses: https://github.com/redhat-actions/push-to-registry@v2
        with:
          registry: docker.io
          image: ${{ secrets.DOCKERHUB_USER }}/${{ vars.DOCKERHUB_IMAGE_NAME }}
          tags: ${{ env.GITHUB_REF_NAME }} latest
 
