name: Build with buildah and Push to Container Registry
on: 
  push:
    branches:
      - main
      - develop
    tags:
      - '**'
jobs:
  build_and_push:
    runs-on: default
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
      - name: Build the Image
        uses: https://github.com/redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.IMAGE_NAME }}
          tags: ${{ env.GITHUB_REF_NAME }} latest
          containerfiles: |
            ./Containerfile
      - name: Login to the registry
        uses: https://github.com/redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          auth_file_path: $HOME/.docker/config.json
      - name: Push the image to the registry
        uses: https://github.com/redhat-actions/push-to-registry@v2
        with:
          tags: ${{ vars.IMAGE_NAME }}:${{ env.GITHUB_REF_NAME }}
      - name: Push tags to latest
        if: startsWith(github.ref, 'refs/tags/v')
        uses: https://github.com/redhat-actions/push-to-registry@v2
        with:
          tags: ${{ vars.IMAGE_NAME }}:latest

      
