name: Build on Push
run-name: ${{ forgejo.actor }} has pushed
on: [push]
jobs:
  Print-A-Env:
    runs-on: default
    steps:
      - name: Check out the repository code
        uses: actions/checkout@v4
      - name: Build the Image
        uses: https://github.com/redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.IMAGE_NAME }}
          tags: ${{ env.GITHUB_REF_NAME }}
          containerfiles: |
            ./Containerfile
      - name: Login to the registry
        uses: https://github.com/redhat-actions/podman-login@v1
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          auth_file_path: $HOME/.docker/config.json
      
