name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: docker
    steps:
      - run: sudo apt-get update && sudo apt-get install buildah
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Buildah Action
        id: build-image
        uses: https://github.com/redhat-actions/buildah-build@v2
        with:
          image: docker.io/schieberegister/http-to-https
          tags: latest
          containerfiles: |
            ./Dockerfile
